CREATE DATABASE IF NOT EXISTS PROJETO_SISTEMA_DIST DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;

USE PROJETO_SISTEMA_DIST;

DROP TABLE IF EXISTS USUARIO;

CREATE TABLE USUARIO(
	PK_USUARIO 					INT COMMENT 'ID DO USUARIO',
	
	EMAIL 						VARCHAR(30) NOT NULL UNIQUE COMMENT 'EMAIL DO USUARIO',
	
	SENHA 						VARCHAR(255) NOT NULL COMMENT 'SENHA DO USUARIO',
	
	NOME 						VARCHAR(100) NOT NULL COMMENT 'NOME DO USUARIO',
	
	DATA_CADASTRO 				TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT 'DATA E HORA QUE O USUARIO FOI CADASTRADO',
	
	SEXO 						ENUM('M','F') NOT NULL COMMENT 'M - MASCULINO, F - FEMININO',
	
	SITUACAO 					BOOLEAN  NOT NULL DEFAULT FALSE	COMMENT 'TRUE - USUARIO ATIVO, FALSE - USUARIO INATIVO'
);

ALTER TABLE USUARIO ADD CONSTRAINT PROJETO_PK_USUARIO PRIMARY KEY (PK_USUARIO);

ALTER TABLE USUARIO CHANGE PK_USUARIO PK_USUARIO INT NOT NULL UNIQUE AUTO_INCREMENT;

DROP TABLE IF EXISTS EMAIL;

CREATE TABLE EMAIL(
	PK_EMAIL					INT COMMENT 'ID DO EMAIL',
	
	ASSUNTO						VARCHAR(255) NOT NULL COMMENT 'ASSUNTO DO E-MAIL',
	
	FK_USUARIO_EMAIL_DE 		INT NOT NULL COMMENT 'USUARIO QUE ENVIOU O EMAIL',
		
	FK_USUARIO_EMAIL_PARA	 	INT NOT NULL COMMENT 'USUARIO QUE RECEBEU O EMAIL'
);

ALTER TABLE EMAIL ADD CONSTRAINT PROJETO_PK_EMAIL PRIMARY KEY (PK_EMAIL);

ALTER TABLE EMAIL CHANGE PK_EMAIL PK_EMAIL INT NOT NULL UNIQUE AUTO_INCREMENT;

DROP TABLE IF EXISTS MENSAGEM;

CREATE TABLE MENSAGEM(
	CONTEUDO					VARCHAR(255) NOT NULL COMMENT 'CONTEUDO DA MENSAGEM',
	
	DATA_MENSAGEM				TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT 'DATA DO ENVIO DA MENSAGEM',
	
	SITUACAO					BOOLEAN DEFAULT FALSE COMMENT 'TRUE - MENSAGEM LIDA, FALSE - MENSAGEM NÃO LIDA',
	
	FK_EMAIL_MENSAGEM			INT NOT NULL COMMENT 'ID DO EMAIL',
	
	FK_USUARIO_MENSAGEM			INT NOT NULL COMMENT 'ID DO USUARIO QUE ENVIOU A MENSAGEM PARA O EMAIL X'
);

ALTER TABLE MENSAGEM ADD CONSTRAINT PROJETO_FK_EMAIL_MENSAGEM FOREIGN KEY (FK_EMAIL_MENSAGEM) REFERENCES EMAIL (PK_EMAIL);

ALTER TABLE MENSAGEM ADD CONSTRAINT PROJETO_FK_USUARIO_MENSAGEM FOREIGN KEY (FK_USUARIO_MENSAGEM) REFERENCES USUARIO (PK_USUARIO);

DROP TABLE IF EXISTS ARQUIVO;

CREATE TABLE ARQUIVO(
	PK_ARQUIVO 					INT COMMENT 'ID DO ARQUIVO',
	
	NOME 						VARCHAR(50) NOT NULL COMMENT 'NOME DO ARQUIVO',

	DESCRICAO 					VARCHAR(50) NOT NULL COMMENT 'DESCRICAO DO CONTEÚDO DO ARQUIVO',
	
	TIPO 						VARCHAR(10) NOT NULL COMMENT 'TIPO DO ARQUIVO PDF, CSV,XLS,DOCX,PNG, ETC',
	
	TAMANHO 					INT NOT NULL COMMENT 'TAMANHO EM DISCO DO ARQUIVO',
	
	CAMINHO 					VARCHAR(20) NOT NULL UNIQUE COMMENT 'LOCAL DO ARQUIVO',	
	
	DATA_CRIACAO 				TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT 'DATA QUE O ARQUIVO FOI CRIADO',
	
	FK_USUARIO_ARQUIVO			INT NOT NULL COMMENT 'USUARIO QUE CRIOU O ARQUIVO'		
);

ALTER TABLE ARQUIVO ADD CONSTRAINT PROJETO_PK_ARQUIVO PRIMARY KEY (PK_ARQUIVO);

ALTER TABLE ARQUIVO CHANGE PK_ARQUIVO PK_ARQUIVO INT NOT NULL UNIQUE AUTO_INCREMENT;

ALTER TABLE ARQUIVO ADD CONSTRAINT PROJETO_FK_USUARIO_ARQUIVO FOREIGN KEY (FK_USUARIO_ARQUIVO) REFERENCES USUARIO (PK_USUARIO);

DROP TABLE IF EXISTS TAREFA;

CREATE TABLE TAREFA(
	PK_TAREFA 					INT COMMENT 'ID DA TAREFA',
	
	TITULO 						VARCHAR(20) NOT NULL COMMENT 'TITULO DA TAREFA',
	
	DESCRICAO 					VARCHAR(255) NOT NULL COMMENT 'DESCRICAO DA TAREFA',

	DATA_ENVIO					TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT 'DATA QUE A TAREFA FOI ENVIADA',

	SITUACAO					ENUM('A', 'R', 'M') NOT NULL COMMENT 'A - TAREFA ACEITA, R - TAREFA REJEITADA, M - TAREFA MODIFICADA',
	
	DATA_LIMITE					DATE NOT NULL COMMENT 'DATA LIMITE PARA MUDAR A SITUAÇÃO DA TAREFA',
	
	FK_USUARIO_TAREFA_DE		INT NOT NULL COMMENT 'USUARIO QUE ENVIOU A TAREFA',
	
	FK_USUARIO_TAREFA_PARA		INT NOT NULL COMMENT 'USUARIO QUE RECEBEU A TAREFA'	
);

ALTER TABLE TAREFA ADD CONSTRAINT PROJETO_PK_TAREFA PRIMARY KEY (PK_TAREFA);

ALTER TABLE TAREFA CHANGE PK_TAREFA PK_TAREFA INT NOT NULL UNIQUE AUTO_INCREMENT;

ALTER TABLE TAREFA ADD CONSTRAINT PROJETO_FK_USUARIO_TAREFA_DE FOREIGN KEY (FK_USUARIO_TAREFA_DE) REFERENCES USUARIO (PK_USUARIO);

ALTER TABLE TAREFA ADD CONSTRAINT PROJETO_FK_USUARIO_TAREFA_PARA FOREIGN KEY (FK_USUARIO_TAREFA_PARA) REFERENCES USUARIO (PK_USUARIO);